class AddActivities < ActiveRecord::Migration[7.0]
  def change
    create_table :activities do |t|
      t.string :name
      t.timestamps
    end
    
    Activity.create(name: "Running")
    Activity.create(name: "Jogging")
    Activity.create(name: "Biking")
    Activity.create(name: "Swimming")
    Activity.create(name: "Rowing")
    Activity.create(name: "Elliptical")
    Activity.create(name: "Jump rope")
    Activity.create(name: "Stair climbing")
    Activity.create(name: "HIIT (High Intensity Interval Training)")
    Activity.create(name: "Aerobics")
    Activity.create(name: "Weight lifting")
    Activity.create(name: "Resistance training")
    Activity.create(name: "Bodyweight exercises")
    Activity.create(name: "CrossFit")
    Activity.create(name: "Powerlifting")
    Activity.create(name: "Kettlebell training")
    Activity.create(name: "TRX")
    Activity.create(name: "Plyometrics")
    Activity.create(name: "Strongman")
    Activity.create(name: "Circuit training")
    Activity.create(name: "Hatha")
    Activity.create(name: "Vinyasa")
    Activity.create(name: "Ashtanga")
    Activity.create(name: "Bikram")
    Activity.create(name: "Restorative")
    Activity.create(name: "Iyengar")
    Activity.create(name: "Kundalini")
    Activity.create(name: "Yin")
    Activity.create(name: "Anusara")
    Activity.create(name: "Jivamukti")
    Activity.create(name: "Mat Pilates")
    Activity.create(name: "Reformer Pilates")
    Activity.create(name: "Cadillac Pilates")
    Activity.create(name: "Tower Pilates")
    Activity.create(name: "Wunda Chair Pilates")
    Activity.create(name: "Barrel Pilates")
    Activity.create(name: "Allegro Pilates")
    Activity.create(name: "Fletcher Pilates")
    Activity.create(name: "Contemporary Pilates")
    Activity.create(name: "Winsor Pilates")
    Activity.create(name: "Ballet")
    Activity.create(name: "Jazz")
    Activity.create(name: "Hip hop")
    Activity.create(name: "Tap")
    Activity.create(name: "Contemporary")
    Activity.create(name: "Ballroom")
    Activity.create(name: "Latin")
    Activity.create(name: "Swing")
    Activity.create(name: "Salsa")
    Activity.create(name: "Zumba")
    Activity.create(name: "Karate")
    Activity.create(name: "Taekwondo")
    Activity.create(name: "Judo")
    Activity.create(name: "Kung Fu")
    Activity.create(name: "Aikido")
    Activity.create(name: "Krav Maga")
    Activity.create(name: "Boxing")
    Activity.create(name: "Kickboxing")
    Activity.create(name: "MMA")
    Activity.create(name: "Wrestling")
    Activity.create(name: "Basketball")
    Activity.create(name: "Football")
    Activity.create(name: "Soccer")
    Activity.create(name: "Tennis")
    Activity.create(name: "Volleyball")
    Activity.create(name: "Golf")
    Activity.create(name: "Baseball")
    Activity.create(name: "Softball")
    Activity.create(name: "Hockey")
    Activity.create(name: "Swimming")
    Activity.create(name: "Hiking")
    Activity.create(name: "Camping")

  
end
